json_data = '''{
    "version": 2,
    "query": "java",
    "location": "austin, tx",
    "dupefilter": true,
    "highlight": false,
    "radius": 25,
    "start": 1,
    "end": 10,
    "totalResults": 547,
    "pageNumber": 0,
    "results": [
        {
            "jobtitle": "Java Developer",
            "company": "XYZ Corp",
            "city": "Austin",
            "state": "TX",
            "country": "US",
            "formattedLocation": "Austin, TX",
            "source": "Dice",
            "date": "Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": "looking for an object-oriented Java Developer... Java Servlets, HTML, JavaScript, AJAX, Struts, Struts2, JSF desirable. Familiarity with Tomcat and the Java...",
            "url": "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown": "indeed_clk(this, '0000');",
            "latitude": 30.27127,
            "longitude": -97.74103,
            "jobkey": "12345",
            "sponsored": false,
            "expired": false,
            "indeedApply": true,
            "formattedLocationFull": "Austin, TX",
            "formattedRelativeTime": "11 hours ago"
        },
        {
            "jobtitle": "React Engineer",
            "company": "Evil Corp",
            "city": "Charlotte",
            "state": "NC",
            "country": "US",
            "formattedLocation": "Charlotte, NC",
            "source": "Dice",
            "date": "Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": "looking for an object-oriented Java Developer... Java Servlets, HTML, JavaScript, AJAX, Struts, Struts2, JSF desirable. Familiarity with Tomcat and the Java...",
            "url": "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown": "indeed_clk(this, '0000');",
            "latitude": 30.27127,
            "longitude": -97.74103,
            "jobkey": "12345",
            "sponsored": false,
            "expired": false,
            "indeedApply": true,
            "formattedLocationFull": "Charlotte, NC",
            "formattedRelativeTime": "11 hours ago"
        },
        {
            "jobtitle": "JavaScript Developer",
            "company": "ABC Corp",
            "city": "Charlotte",
            "state": "NC",
            "country": "US",
            "formattedLocation": "Charlotte, NC",
            "source": "Dice",
            "date": "Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": "looking for an object-oriented Java Developer... Java Servlets, HTML, JavaScript, AJAX, Struts, Struts2, JSF desirable. Familiarity with Tomcat and the Java...",
            "url": "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown": "indeed_clk(this, '0000');",
            "latitude": 30.27127,
            "longitude": -97.74103,
            "jobkey": "12345",
            "sponsored": false,
            "expired": false,
            "indeedApply": true,
            "formattedLocationFull": "Charlotte, NC",
            "formattedRelativeTime": "11 hours ago"
        },
        {
            "jobtitle": "Python API Developer",
            "company": "LMNOP Corp",
            "city": "Charlotte",
            "state": "NC",
            "country": "US",
            "formattedLocation": "Charlotte, NC",
            "source": "Dice",
            "date": "Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": "looking for an object-oriented Java Developer... Java Servlets, HTML, JavaScript, AJAX, Struts, Struts2, JSF desirable. Familiarity with Tomcat and the Java...",
            "url": "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown": "indeed_clk(this, '0000');",
            "latitude": 30.27127,
            "longitude": -97.74103,
            "jobkey": "12345",
            "sponsored": false,
            "expired": false,
            "indeedApply": true,
            "formattedLocationFull": "Charlotte, NC",
            "formattedRelativeTime": "11 hours ago"
        },
        {
            "jobtitle": "Java Developer",
            "company": "XYZ Corp",
            "city": "Austin",
            "state": "TX",
            "country": "US",
            "formattedLocation": "Austin, TX",
            "source": "Dice",
            "date": "Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": "looking for an object-oriented Java Developer... Java Servlets, HTML, JavaScript, AJAX, Struts, Struts2, JSF desirable. Familiarity with Tomcat and the Java...",
            "url": "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown": "indeed_clk(this, '0000');",
            "latitude": 30.27127,
            "longitude": -97.74103,
            "jobkey": "12345",
            "sponsored": false,
            "expired": false,
            "indeedApply": true,
            "formattedLocationFull": "Austin, TX",
            "formattedRelativeTime": "11 hours ago"
        }
    ]
}'''
