"""add user_settings table

Revision ID: e1f886449e1a
Revises: 560fcda868d3
Create Date: 2020-08-14 10:15:07.279263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f886449e1a'
down_revision = '560fcda868d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_radius', sa.Integer(), nullable=False),
    sa.Column('tech_one', sa.String(length=50), nullable=False),
    sa.Column('tech_two', sa.String(length=50), nullable=False),
    sa.Column('tech_three', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
