"""add bookmarks join table

Revision ID: 560fcda868d3
Revises: b59c65c6c022
Create Date: 2020-08-14 09:48:01.033983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560fcda868d3'
down_revision = 'b59c65c6c022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'posting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
