"""add all tables

Revision ID: e7643e8e4c66
Revises: 
Create Date: 2020-08-31 13:34:24.896571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7643e8e4c66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avg_mkt_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_terms', sa.String(length=100), nullable=False),
    sa.Column('search_loc', sa.String(length=100), nullable=False),
    sa.Column('formatted_sal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_terms', sa.String(length=100), nullable=False),
    sa.Column('search_loc', sa.String(length=100), nullable=False),
    sa.Column('pos_counts_mkt', sa.Integer(), nullable=True),
    sa.Column('pos_pcts_mkt', sa.Float(), nullable=True),
    sa.Column('pos_overall_mkt_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_terms', sa.String(length=100), nullable=False),
    sa.Column('search_loc', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('formatted_sal', sa.Integer(), nullable=True),
    sa.Column('js_count', sa.Integer(), nullable=True),
    sa.Column('python_count', sa.Integer(), nullable=True),
    sa.Column('ruby_count', sa.Integer(), nullable=True),
    sa.Column('net_count', sa.Integer(), nullable=True),
    sa.Column('java_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'posting_id')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_radius', sa.Integer(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searches')
    op.drop_table('bookmarks')
    op.drop_table('users')
    op.drop_table('postings')
    op.drop_table('market_metrics')
    op.drop_table('avg_mkt_salaries')
    # ### end Alembic commands ###
